// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const getUserPosts = `-- name: GetUserPosts :many
SELECT users.id, users.name, users.age, posts.id, posts.user_id FROM users
LEFT JOIN posts ON posts.user_id = users.id
ORDER BY users.id
`

type GetUserPosts struct {
	User User   `db:"user" json:"user"`
	Post []Post `db:"post" json:"post"`
}

type GetUserPostsRow struct {
	User User `db:"user" json:"user"`
	Post Post `db:"post" json:"post"`
}

// @group-by users.id
func (q *Queries) GetUserPosts(ctx context.Context) ([]GetUserPosts, error) {
	rows, err := q.db.QueryContext(ctx, getUserPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPosts

	for rows.Next() {
		var i GetUserPostsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Name,
			&i.User.Age,
			&i.Post.ID,
			&i.Post.UserID,
		); err != nil {
			return nil, err
		}

		if len(items) == 0 || i.User.ID != items[len(items)-1].User.ID {
			items = append(items, GetUserPosts{
				User: i.User,
				Post: []Post{i.Post},
			})
		} else {
			items[len(items)-1].Post = append(items[len(items)-1].Post, i.Post)
		}
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
