// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querytest

import (
	"database/sql"
)

type Bar struct {
	ID int32
}

type Comment struct {
	ID     int32
	UserID int32
	PostID int32
}

type Foo struct {
	ID    int32
	BarID sql.NullInt32
}

type Post struct {
	ID     int32
	UserID int32
}
