// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID     int32 `db:"id" json:"id"`
	UserID int32 `db:"user_id" json:"user_id"`
}

type User struct {
	ID   int32       `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Age  pgtype.Int4 `db:"age" json:"age"`
}
