// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querytest

type Post struct {
	ID     int32
	UserID int32
	Title  string
	ApiKey string
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
