// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
)

const getUserExcludeMultiple = `-- name: GetUserExcludeMultiple :one
SELECT id, name FROM users WHERE id = $1
`

type GetUserExcludeMultipleRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetUserExcludeMultiple(ctx context.Context, id int32) (GetUserExcludeMultipleRow, error) {
	row := q.db.QueryRowContext(ctx, getUserExcludeMultiple, id)
	var i GetUserExcludeMultipleRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUserExcludeWithEmbed = `-- name: GetUserExcludeWithEmbed :one
SELECT users.id, users.name, users.email FROM users WHERE id = $1
`

type GetUserExcludeWithEmbedRow struct {
	User User
}

func (q *Queries) GetUserExcludeWithEmbed(ctx context.Context, id int32) (GetUserExcludeWithEmbedRow, error) {
	row := q.db.QueryRowContext(ctx, getUserExcludeWithEmbed, id)
	var i GetUserExcludeWithEmbedRow
	err := row.Scan(&i.User.ID, &i.User.Name, &i.User.Email)
	return i, err
}

const getUserWithoutPassword = `-- name: GetUserWithoutPassword :one
SELECT id, name, email FROM users WHERE id = $1
`

type GetUserWithoutPasswordRow struct {
	ID    int32
	Name  string
	Email string
}

func (q *Queries) GetUserWithoutPassword(ctx context.Context, id int32) (GetUserWithoutPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, getUserWithoutPassword, id)
	var i GetUserWithoutPasswordRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const joinEmbedExclude = `-- name: JoinEmbedExclude :one
SELECT users.id, users.name, users.email, posts.id, posts.user_id, posts.title
FROM posts
INNER JOIN users ON posts.user_id = users.id
WHERE posts.id = $1
`

type JoinEmbedExcludeRow struct {
	User User
	Post Post
}

func (q *Queries) JoinEmbedExclude(ctx context.Context, id int32) (JoinEmbedExcludeRow, error) {
	row := q.db.QueryRowContext(ctx, joinEmbedExclude, id)
	var i JoinEmbedExcludeRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.Post.ID,
		&i.Post.UserID,
		&i.Post.Title,
	)
	return i, err
}

const joinEmbedExcludeAlias = `-- name: JoinEmbedExcludeAlias :one
SELECT u.id, u.name, u.email, p.id, p.user_id, p.title
FROM posts p
INNER JOIN users u ON p.user_id = u.id
WHERE p.id = $1
`

type JoinEmbedExcludeAliasRow struct {
	User User
	Post Post
}

// Uses table aliases (u, p) but exclude with table names - validates join+embed+exclude with aliased from clause
func (q *Queries) JoinEmbedExcludeAlias(ctx context.Context, id int32) (JoinEmbedExcludeAliasRow, error) {
	row := q.db.QueryRowContext(ctx, joinEmbedExcludeAlias, id)
	var i JoinEmbedExcludeAliasRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.Post.ID,
		&i.Post.UserID,
		&i.Post.Title,
	)
	return i, err
}

const joinEmbedExcludeQualified = `-- name: JoinEmbedExcludeQualified :one
SELECT users.id, users.name, users.email, posts.id, posts.user_id, posts.title
FROM posts
INNER JOIN users ON posts.user_id = users.id
WHERE posts.id = $1
`

type JoinEmbedExcludeQualifiedRow struct {
	User User
	Post Post
}

func (q *Queries) JoinEmbedExcludeQualified(ctx context.Context, id int32) (JoinEmbedExcludeQualifiedRow, error) {
	row := q.db.QueryRowContext(ctx, joinEmbedExcludeQualified, id)
	var i JoinEmbedExcludeQualifiedRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.Post.ID,
		&i.Post.UserID,
		&i.Post.Title,
	)
	return i, err
}
