// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bar struct {
	ID int32
}

type Comment struct {
	ID     int32
	UserID int32
	PostID int32
}

type Foo struct {
	ID    int32
	BarID pgtype.Int4
}

type Post struct {
	ID     int32
	UserID int32
}
