// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const rightJoin = `-- name: RightJoin :many
SELECT f.id, f.bar_id, b.id
FROM foo f
RIGHT JOIN bar b ON b.id = f.bar_id
WHERE f.id = $1
`

type RightJoinRow struct {
	FooID sql.NullInt32
	BarID sql.NullInt32
	ID_2  int32
}

func (q *Queries) RightJoin(ctx context.Context, id int32) ([]RightJoinRow, error) {
	rows, err := q.db.Query(ctx, rightJoin, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RightJoinRow
	for rows.Next() {
		var i RightJoinRow
		if err := rows.Scan(&i.FooID, &i.BarID, &i.ID_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aliasJoin = `-- name: AliasJoin :many
SELECT p.user_id, c.user_id
FROM posts p
JOIN comments c ON c.post_id = p.id
`

type AliasJoinRow struct {
	PostUserID    int32
	CommentUserID int32
}

func (q *Queries) AliasJoin(ctx context.Context) ([]AliasJoinRow, error) {
	rows, err := q.db.Query(ctx, aliasJoin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AliasJoinRow
	for rows.Next() {
		var i AliasJoinRow
		if err := rows.Scan(&i.PostUserID, &i.CommentUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aliasJoinLong = `-- name: AliasJoinLong :many
SELECT pt.user_id, ct.user_id
FROM posts pt
JOIN comments ct ON ct.post_id = pt.id
`

type AliasJoinLongRow struct {
	PtUserID int32
	CtUserID int32
}

func (q *Queries) AliasJoinLong(ctx context.Context) ([]AliasJoinLongRow, error) {
	rows, err := q.db.Query(ctx, aliasJoinLong)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AliasJoinLongRow
	for rows.Next() {
		var i AliasJoinLongRow
		if err := rows.Scan(&i.PtUserID, &i.CtUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tableName = `-- name: TableName :one
SELECT foo.id
FROM foo
JOIN bar ON foo.bar_id = bar.id
WHERE bar.id = $1 AND foo.id = $2
`

type TableNameParams struct {
	BarID int32
	FooID int32
}

func (q *Queries) TableName(ctx context.Context, arg TableNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, tableName, arg.BarID, arg.FooID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
